apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-alloy-rbac
  namespace: argocd
  annotations:
    # Up before Alloy syncs so the SA has perms by the time it starts watching.
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/vedantaggrawal/repo-platform-gitops.git
    targetRevision: HEAD
    path: manifests/alloy-rbac/{{ .Values.env }}
    directory:
      recurse: true
  destination:
    server: {{ .Values.cluster }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: {{ .Values.prune }}
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
