apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/vedantaggrawal/repo-platform-gitops.git
    targetRevision: HEAD
    path: network-policies/{{ .Values.env }}
    directory:
      recurse: true
  destination:
    server: {{ .Values.cluster }}
    namespace: default
  syncPolicy:
    automated:
      prune: {{ .Values.prune }}
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
