apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-minio-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/vedantaggrawal/repo-platform-gitops.git
    targetRevision: HEAD
    path: manifests/minio-init/{{ .Values.env }}
    directory:
      recurse: true
  destination:
    server: {{ .Values.cluster }}
    namespace: monitoring-storage
  syncPolicy:
    automated:
      prune: {{ .Values.prune }}
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
