apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-onboarding
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/vedantaggrawal/repo-platform-gitops.git
              revision: HEAD
              files:
                - path: 'clusters/*.yaml'
          - git:
              repoURL: https://github.com/vedantaggrawal/repo-platform-gitops.git
              revision: HEAD
              files:
                - path: 'platform-apps/*/config.yaml'
  template:
    metadata:
      name: '{{env}}-{{path[1]}}'
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: default
      sources:
        - chart: '{{chart}}'
          repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          helm:
            valueFiles:
              - $values/platform-apps/{{path[1]}}/{{env}}/values.yaml
        - repoURL: https://github.com/vedantaggrawal/repo-platform-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: {{prune}}
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 2m
