replicaCount: 3

image:
  tag: "1.0.0-prod"

envVariables:
  ENV: "production"
  LOG_LEVEL: "warn"

canary:
  enabled: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  hosts:
    - host: prod.webserver.internal
      paths:
        - path: /
          pathType: Prefix
