replicaCount: 1

image:
  tag: "1.0.0-dev"

envVariables:
  ENV: "development"
  LOG_LEVEL: "debug"

ingress:
  enabled: true
  hosts:
    - host: dev.webserver.internal
      paths:
        - path: /
          pathType: Prefix
