replicaCount: 2

image:
  tag: "1.0.0-stg"

envVariables:
  ENV: "staging"
  LOG_LEVEL: "info"

ingress:
  enabled: true
  hosts:
    - host: stg.webserver.internal
      paths:
        - path: /
          pathType: Prefix
